### ISSUE TITLE
Geo replication 

### ISSUE THREAD

**Issue by paphillon** [rayokota/keta#136]
Hi,

Thanks for this fantastic project; I can't wait to try it! There is one particular use case where we want multi-geo availability if the primary site goes down. In Kafka the replication is possible with MirrorMaker or even a simple producer consumer to distinct Kafka clusters, if we apply the the same to the topics backing this cache, should that suffice or there is something additional that will be required? 

Thanks,
Vikram

**Comment by rayokota** [comment]
Yes, that should suffice.
